Controllers/ResisterUserController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MiniProject.Models;
using System.Data.SqlClient;
using System.Data;
using System;
using System.Linq;

namespace MiniProject.Controllers
{
    public class ResisterUserController : Controller
    {
        //GET
        public ActionResult Create(bool isTrue)
        {
            ViewData["isTrue"] = isTrue;
            ResisterUser model = new ResisterUser();
            model.drdncity = DropDownCity();
            return View(model);

        }
        // POST: ResisterUserController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ResisterUser ruc)
        {
            try
            {
                ResisterUser.registerUser(ruc);
                return RedirectToAction("Create", new { isTrue = true});
            }
            catch(Exception e)
            {
                return View(e.Message);
            }
        }
        public static List<SelectListItem> DropDownCity()
        {
            List<SelectListItem> items = new List<SelectListItem>();
            SqlConnection cn = new SqlConnection();
            cn.ConnectionString = @"Data Source=(localdb)\ProjectModels;Initial Catalog=MP;Integrated Security=True";
            cn.Open();
            SqlCommand cmd = new SqlCommand();
            cmd.Connection = cn;
            cmd.CommandType = CommandType.Text;
            cmd.CommandText = "Select * from City";
            SqlDataReader dr = cmd.ExecuteReader();

            while (dr.Read())
            {
                items.Add(new SelectListItem
                {
                    Text = dr["CityName"].ToString(),
                    Value = dr["Cityid"].ToString()
                });
            }
            cn.Close();
            return items;
        }

        public ActionResult Login()
        {
            ResisterUser r = new ResisterUser();
            r.LoginName = Request.Cookies["LoginName"];
            r.Password = Request.Cookies["Password"];

            if (r.LoginName != null)
            {
                string Fullame = ResisterUser.isvalidlnlp(r.LoginName, r.Password);
                if (Fullame != null)
                {
                    HttpContext.Session.SetString("LoginName", r.LoginName);
                    HttpContext.Session.SetString("FullName", Fullame);
                    return RedirectToAction("Welcome");
                }
            }
           
            return View(); 
            
        }
        [HttpPost]
        public ActionResult Login(string LoginName, string Password, string RememberMe)
        {
            try
            {
                string fullName = ResisterUser.isvalidlnlp(LoginName, Password);
                HttpContext.Session.SetString("FullName", fullName);
                HttpContext.Session.SetString("LoginName", LoginName);
                if (RememberMe == "on")
                {
                    CookieOptions cos = new CookieOptions();
                    cos.Expires = DateTime.Now.AddDays(1);
                    Response.Cookies.Append("LoginName", LoginName, cos);
                    Response.Cookies.Append("Password", Password, cos);      
                }
                return RedirectToAction("Welcome");
            }
            catch (Exception exception)
            {
                ViewData["Error"] = exception.Message;
                return View("Login", new { ViewBag.Error });
            }
        }

        public ActionResult Welcome()
        {
            string fullName = HttpContext.Session.GetString("FullName");
            if (fullName == null)
            {
                return RedirectToAction("Welcome");
            }
            ViewData["FullName"] = fullName;
            return View();
        }
        public ActionResult Logout()
        {
            HttpContext.Session.Clear();
            Response.Cookies.Delete("LoginName");
            Response.Cookies.Delete("Password");
            return RedirectToAction("Login");
        }

        public ActionResult Update(bool isTrue)
        {
            try
            {
                ViewData["isTrue"] = isTrue;
                string fullName = HttpContext.Session.GetString("FullName");
                string loginName = HttpContext.Session.GetString("LoginName");
                ResisterUser user = new ResisterUser();
                user = ResisterUser.UserByLoginname(loginName);
                user.drdncity = DropDownCity();
                return View(user);
            }
            catch (Exception ex)
            {
                return View();
            }
        }
        [HttpPost]
        public ActionResult Update(string LoginName ,ResisterUser ru1)
        {
            try
            {
                ResisterUser.UpdateUser(LoginName, ru1);
                return RedirectToAction("Update", new { isTrue = true });
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        public ActionResult Showtable()
        {
            SortedDictionary<string,List<ResisterUser>> ru=ResisterUser.marsViewdata();
            return View(ru);
        }




        // GET: ResisterUserController/Details/5
        public ActionResult Details()
        {
            ResisterUser model = new ResisterUser();
            model.drdncity = DropDownCity();
            ResisterUser.ShowCityEntry(model.CityId);
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Details(ResisterUser ru)
        {
            try
            {
                //ResisterUser.ShowCityEntry(ru);
                return View();
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MiniProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MiniProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MiniProject</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ResisterUser" asp-action="Login">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ResisterUser" asp-action="Showtable">ViewAllData</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MiniProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout1ForResi.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        <form action="action_page.php">
            <div class="form_wrapper">
                <div class="form_container">
                    <div class="title_container">
                        <h2>Registration Form</h2>
                    </div>
                    <div class="row clearfix">
                        <div class="">
                            <form>
                                <div class="input_field">
                                    <span><i aria-hidden="true" class="fa fa-envelope"></i></span>
                                    <input type="login name" name="login name" placeholder="Login Name" required />
                                </div>
                                
                                <div class="input_field">
                                    <span><i aria-hidden="true" class="fa fa-lock"></i></span>
                                    <input type="password" name="password" placeholder="Password" required />
                                </div>
                                
                                <div class="input_field">
                                    <span><i aria-hidden="true" class="fa fa-lock"></i></span>
                                    <input type="email" name="email" placeholder="Email"accept="Email" required />
                                </div>
                                
                                <div class="input_field">
                                    <span><i aria-hidden="true" class="fa fa-lock"></i></span>
                                    <input type="CityId" name="CityId" placeholder="CityId" accept="CityId" required />
                                </div>



                               <div class="row clearfix">
                                    <div class="col_half">
                                        <div class="input_field">
                                            <span><i aria-hidden="true" class="fa fa-user"></i></span>
                                            <input type="text" name="Phone Number" placeholder="Phone Number" />
                                        </div>
                                    </div>
                                    <div class="col_half">
                                        <div class="input_field">
                                            <span><i aria-hidden="true" class="fa fa-user"></i></span>
                                            <input type="text" name="Fullname" placeholder="Full Name" required />
                                        </div>
                                    </div>
                                </div>
                                <div class="input_field radio_option">
                                    <input type="radio" name="radiogroup1" id="rd1">
                                    <label for="rd1">Male</label>
                                    <input type="radio" name="radiogroup1" id="rd2">
                                    <label for="rd2">Female</label>
                                      <input type="radio" name="radiogroup1" id="rd2">
                                    <label for="rd2">Others</label>
                                </div>
                                <div class="input_field select_option">
                                    <select>
                                        <option>Select City Name</option>
                                        <option>Option 1</option>
                                        <option>Option 2</option>
                                    </select>
                                    <div class="select_arrow"></div>
                                </div>
                                <input class="button" type="submit" value="Register" />
                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </form>
    </div>
</body>
</html>

Views/Shared/_LayoutMy.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body style="background-color:aliceblue">

    <header>
        <h1 style="text-align:center; color:black">All City Details</h1>
    </header>
  
    <div class="content">
        @RenderBody()
    </div>

    <style>
        header {
            height: 100px;
            width: 100%;

        }

        nav {
            float: left;
            width: 200px;
            height: 250px;
   
        }

        .content {
            background-color: aliceblue;
            padding: 20px;
        }

        footer {
            width: 100%;
            height: 50px;
            float: right;
            text-align: center;
        }
    </style>
</body>
</html>